title: Genius Sheets
description: "Streamline financial reporting with seamless QuickBooks integration into Excel and Google Sheets."
url: "https://geniussheets.us"
baseurl: ""

email: info@geniussheets.us
location: "Philadelphia, PA"

google_analytics: G-72PG6GMT2S

social:
  linkedin: "https://www.linkedin.com/company/geniussheets"
  twitter: "https://x.com/geniussheetsdev"
  youtube: "https://www.youtube.com/@GeniusSheets"

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
